Resources:
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs16.x
      Role: !GetAtt LambdaRole.Arn
      FunctionName: CFLambdaTest
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = async (event) => {
              return {
                statusCode: 200,
                body: JSON.stringify({
                  id: 100,
                  message: "hello from CF Stack!"
                })
              }
          }
      TracingConfig:
        Mode: Active

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/CFLambdaTest
      RetentionInDays: 90

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CFLambdaTest-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: CFLambdaTest-lambdapolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/CFLambdaTest:*
