AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 3
      MemorySize: 128
      InlineCode: |
        exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({
                id: 100,
                message: "hello from CF Stack!"
              })
            }
        }
      Handler: index.handler
      Runtime: nodejs16.x
